language: node_js
node_js:
  - "10"

# Travis-CI Caching
cache:
  directories:
    - node_modules

# S: Build Lifecycle
install:
  - npm install

before_script:
  - git submodule init
  - git submodule update
  - cd themes/landscape && git checkout 73a23c51f8487cfcd7c6deec96ccc7543960d350 && cd ../..
  - npm install -g hexo-cli

# 无其他依赖项所以执行npm run build 构建就行了
script:
  - hexo generate
  - hexo deploy

after_script:

# E: Build LifeCycle

#指定分支，只有指定的分支提交时才会运行脚本
branches:
  only:
    - master
env:
 global:
   # 我将其添加到了travis-ci的环境变量中
   #- GH_REF: github.com/yimogit/metools.git
