language: node_js
node_js:
- '16'

git:
  depth: false
  quiet: true
  submodules: true
branches:
  only:
    - master

cache:
  directories:
    - node_modules

before_install:
#  - git submodule foreach git pull origin master
  - npm install -g hexo-cli
  - cd article && git pull origin master && cd ..
install:
  - npm install
script:
  - hexo clean
  - hexo algolia
  - hexo generate --silent

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: docs
  repo: weizhimiao/weizhimiao.github.io
  target_branch: gh-pages
  keep_history: false
  project_name: xylsh
  email: zhimiao2008@gmail.com
  name: zhimiao
  committer_from_gh: false
  allow_empty_commit: true
  verbose: true
  on:
    branch: master


